# Generated by Django 3.0 on 2021-06-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('ReviewerID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=200)),
                ('MiddleInitial', models.CharField(blank=True, max_length=1, null=True)),
                ('LastName', models.CharField(max_length=200)),
                ('Affiliation', models.CharField(max_length=200)),
                ('Department', models.CharField(max_length=200)),
                ('CellNumber', models.CharField(max_length=200)),
                ('WorkNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('Address', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('ZipCode', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200, null=True, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('NumberOfReviews', models.IntegerField(default=0)),
                ('DateJoined', models.CharField(default='2021-06-28T03:04', max_length=200)),
                ('OtherDescription', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
