# Generated by Django 3.0 on 2021-06-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='DateJoined',
            field=models.CharField(default='2021-06-28T04:07', max_length=200),
        ),
    ]
