# Generated by Django 3.0 on 2021-06-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_auto_20210628_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='DateJoined',
            field=models.CharField(default='2021-06-28T04:37', max_length=200),
        ),
    ]
