# Generated by Django 3.0 on 2021-06-28 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0004_auto_20210628_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='DateJoined',
            field=models.CharField(default='2021-06-28T05:42', max_length=200),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ReviewID', models.AutoField(primary_key=True, serialize=False)),
                ('AppropriatenessOfTopic', models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=1)),
                ('ReviewerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewer.Reviewer')),
            ],
        ),
    ]
