# Generated by Django 3.0 on 2021-07-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0005_auto_20210708_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ReviewSubmission',
            field=models.CharField(default='2021-07-10T07:02', max_length=200),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='DateJoined',
            field=models.CharField(default='2021-07-10T07:02', max_length=200),
        ),
    ]
