# Generated by Django 3.0 on 2021-06-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0005_auto_20210628_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='DateJoined',
            field=models.CharField(default='2021-06-28T05:52', max_length=200),
        ),
    ]
