# Generated by Django 3.0 on 2021-06-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0006_auto_20210628_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='CitationOfPreviousWork',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='ClarityOfMainMessage',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='Mechanics',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='OrganizationOfPaper',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='Originality',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='OverallRating',
            field=models.IntegerField(choices=[(1, 'Definitely should not accept paper'), (2, 'Probably should not accept paper'), (3, 'Uncertain about acceptance of paper'), (4, 'Probably should accept paper'), (5, 'Definitely should accept paper')], default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='PotentialInterestInTopic',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='ScopeOfCoverage',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='SuitabilityForPresentation',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='SupportiveEvidence',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='TechnicalQuality',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='TimelinessOfTopic',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=1),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='DateJoined',
            field=models.CharField(default='2021-06-28T05:59', max_length=200),
        ),
    ]
