# Generated by Django 3.0 on 2021-07-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0007_auto_20210713_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ReviewSubmission',
            field=models.CharField(default='2021-07-13T22:07', max_length=200),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='DateJoined',
            field=models.CharField(default='2021-07-13T22:07', max_length=200),
        ),
    ]
