# Generated by Django 3.0 on 2021-06-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0007_auto_20210628_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ContentComments',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='OralComments',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='OverallComments',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='WrittenComments',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='DateJoined',
            field=models.CharField(default='2021-06-28T06:25', max_length=200),
        ),
    ]
