# Generated by Django 3.0 on 2021-07-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0008_auto_20210713_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ReviewSubmission',
            field=models.CharField(default='2021-07-14T04:14', max_length=200),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='DateJoined',
            field=models.CharField(default='2021-07-14T04:14', max_length=200),
        ),
    ]
