# Generated by Django 3.0 on 2021-06-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0012_auto_20210628_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='PaperTitle',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='ReviewSubmission',
            field=models.CharField(default='2021-06-28T19:12', max_length=200),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='DateJoined',
            field=models.CharField(default='2021-06-28T19:12', max_length=200),
        ),
    ]
