# Generated by Django 3.0 on 2021-07-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0013_auto_20210714_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ReviewSubmission',
            field=models.CharField(default='2021-07-14T06:09', max_length=200),
        ),
    ]
