# Generated by Django 3.0 on 2021-07-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0018_auto_20210701_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ReviewSubmission',
            field=models.CharField(default='2021-07-01T00:32', max_length=200),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='DateJoined',
            field=models.CharField(default='2021-07-01T00:32', max_length=200),
        ),
    ]
