# Generated by Django 3.0 on 2021-06-28 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('TopicID', models.AutoField(primary_key=True, serialize=False)),
                ('TopicName', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewerTopic',
            fields=[
                ('ReviewerTopicID', models.AutoField(primary_key=True, serialize=False)),
                ('ReviewerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewer.Reviewer')),
                ('TopicID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.Topic')),
            ],
        ),
    ]
