# Generated by Django 3.0 on 2021-07-01 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '__first__'),
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperTopic',
            fields=[
                ('ReviewerTopicID', models.AutoField(primary_key=True, serialize=False)),
                ('PaperID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.Paper')),
                ('TopicID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.Topic')),
            ],
        ),
    ]
