# Generated by Django 3.0 on 2021-07-04 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_papertopic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='papertopic',
            old_name='ReviewerTopicID',
            new_name='PaperTopicID',
        ),
    ]
