# Generated by Django 3.0 on 2021-07-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0012_auto_20210714_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='DateJoined',
        ),
        migrations.AlterField(
            model_name='review',
            name='ReviewSubmission',
            field=models.CharField(default='2021-07-14T06:08', max_length=200),
        ),
    ]
