# Generated by Django 3.0 on 2021-07-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0016_remove_review_reviewsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ReviewSubmission',
            field=models.CharField(default='2021-07-14T13:13', max_length=200),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='DateJoined',
            field=models.CharField(default='2021-07-14T13:13', max_length=200),
        ),
    ]
